const styles = {
  loader: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    height: '200px',
    width: '100px',
    marginTop: '-100px',
    marginLeft: '-50px',
    transform: 'translate(-50%, -50%)',
  },
  glass: {
    position: 'relative',
    height: '100%',
    background: 'rgba(255,255,255,.1)',
    borderRadius: '0% 0% 15% 15%',
    border: '3px solid',
    borderTop: 0,
    borderBottom: '20px solid',
    borderColor: 'rgba(255,255,255,.7)',
    overflow: 'hidden',
  },
  drink: {
    position: 'absolute',
    top: '100%',
    right: 0,
    bottom: 0,
    left: 0,
    background: 'linear-gradient(to bottom, orange, orangered)',
    boxShadow: 'inset 0 2px 1px rgba(255,69,0,.2)',
    opacity: 0.7,
  },
  counter: {
    position: 'relative',
    lineHeight: '200px',
    fontSize: '22px',
    color: 'rgba(255,255,255,1)',
  },
  lemon: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: '79px',
    width: '79px',
    marginTop: '-38px',
    marginRight: '-38px',
    background: 'radial-gradient(#f7f3b6 10%, #d7d26c)',
    borderRadius: '50%',
    border: '4px solid #47582e',
    boxShadow: 'inset 0 0 0 2px #f7f3b6',
  },
  straw: {
    position: 'absolute',
    bottom: '20px',
    right: '30%',
    height: '220px',
    width: '6px',
    background: 'steelblue',
    borderRadius: '0 6px 0 0',
    transform: 'rotate(-18.5deg)',
    transformOrigin: 'left bottom',
    WebkitTransform: 'rotate(-18.5deg)',
    WebkitTransformOrigin: 'left bottom',
  },
  hidden: {
    display: 'none',
  },
  cubes: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  cube: {
    position: 'absolute',
    width: '50px',
    height: '50px',
    background: 'rgba(255,255,255,.3)',
    borderRadius: '10px',
    boxShadow: 'inset 0 0 10px rgba(255,255,255,.6)',
  },

  cube1: {
    bottom: '0',
  },
  cube2: {
    bottom: '45px',
    left: '25px',
    transform: 'rotate(32deg)',
    transformOrigin: 'center bottom',
    WebkitTransform: 'rotate(32deg)',
    WebkitTransformOrigin: 'center bottom',
  },
  cube3: {
    bottom: '90px',
    left: '20px',
    transform: 'rotate(-34deg)',
    transformOrigin: 'center bottom',
    WebkitTransform: 'rotate(-34deg)',
    WebkitTransformOrigin: 'center bottom',
  },

  coaster: {
    width: '130%',
    height: '4px',
    marginLeft: '-15%',
    background: 'steelblue',
    borderRadius: '2px',
  },
  footer: {
    position: 'absolute',
    left: 0,
    top: '50%',
    right: 0,
    marginTop: '120px',
    color: 'steelblue',
  },
};

export default styles;
